site_name: django-http-polling
site_description: A Django Rest Framework package to effortlessly implement efficient polling APIs, enabling applications to easily fetch updates or new data without custom backend logic.
repo_url: https://github.com/JFer11/django-http-polling
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/JFer11">JFer11</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
